# Generated by Django 6.0.1 on 2026-01-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_a", models.IntegerField()),
                ("field_b", models.IntegerField()),
                ("field_c", models.IntegerField()),
                ("field_d", models.IntegerField()),
                ("field_e", models.IntegerField()),
                ("field_f", models.IntegerField()),
                ("field_g", models.IntegerField()),
                ("field_h", models.IntegerField()),
                ("field_i", models.IntegerField()),
                ("field_j", models.IntegerField()),
                ("field_k", models.IntegerField()),
                ("field_l", models.IntegerField()),
                ("field_m", models.IntegerField()),
                ("field_n", models.IntegerField()),
            ],
        ),
    ]
